services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/CET
    volumes:
      - /home/kilian/container_data/sonarr/config:/config
      - /home/kilian/container_data/jellyfin/media/series:/tv
      - /home/kilian/container_data/qbittorrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
