services:
  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "8081:80"
    environment:
      - REGISTRY_TITLE=Hephaistos Local Docker Registry
      - REGISTRY_URL=http://192.168.1.45:5000
      - DELETE_IMAGES="true"
