# Common healthcheck template
&stack-common:
  healthcheck:
    &common-healthcheck
    interval: 2m
    timeout: 10s
    retries: 3
    start_period: 30s


services:
  # Prometheus from scraping logs
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # ports:
    #   - 9090:9090
    restart: unless-stopped
    volumes:
      - prom_config:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - hephaistos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      <<: *common-healthcheck

  # Graphite exporter to expose graphite metrics of TrueNAS
  graphite-exporter:
    image: prom/graphite-exporter:v0.16.0
    container_name: graphite-exporter
    # ports:
    #   - "9109:9109"  # Graphite input
    #   - "9108:9108"  # Prometheus scrapes metrics here
    command:
      - '--graphite.listen-address=:9109'
      - '--web.listen-address=:9108'
    restart: unless-stopped
    networks:
      - hephaistos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9108"]
      <<: *common-healthcheck
  
   # PVE exporter to expose proxmox metrics 
  pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve-exporter
    # ports:
    #   - "9221:9221"
    restart: unless-stopped
    volumes:
      - prom_config:/etc/prometheus:ro
    networks:
      - hephaistos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9221"]
      <<: *common-healthcheck

  # GPU stats exporter
  gpustat-exporter:
    image: 192.168.1.45:5000/gpustat-exporter:latest
    container_name: gpustat-exporter
    restart: unless-stopped
    # ports:
    #   - "9101:9101"
    command:
      - "--scrape.interval=5s"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility
    networks:
      - hephaistos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9101"]
      <<: *common-healthcheck


volumes:
  prom_config:
  prom_data:


networks:
  hephaistos:
    external: true
