services:
  jackett:
    image: lscr.io/linuxserver/jackett:0.22.1999
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/CET
    volumes:
      - /home/kilian/container_data/jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped
