services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.7
    container_name: jellyfin
    network_mode: host
    ports:
      - 8096:8096
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /home/kilian/container_data/jellyfin/media:/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
      
volumes:
  jellyfin_config:
  jellyfin_cache:
