services:
  ghost:
    image: ghost:5
    container_name: ghost
    restart: always
    ports:
      - "2368:2368"
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghostpass
      database__connection__database: ghostdb
      url: https://petits-bouts.com
    volumes:
      - /home/kilian/container_data/ghost/content:/var/lib/ghost/content
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - db
    networks:
        - web

  db:
    image: mysql:8
    container_name: ghost_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - /home/kilian/container_data/ghost/mysql:/var/lib/mysql
    networks:
      - web

networks:
  web:
    external: true