services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /home/kilian/container_data/littlelink:/usr/share/nginx/html
    restart: unless-stopped
